import type { NextPage } from 'next'
import Head from 'next/head'

import { RegistrationContent } from 'components/Registration'

const RegistrationPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Registration Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <RegistrationContent />
    </>
  )
}

export default RegistrationPage
