import type { NextPage } from 'next'
import Head from 'next/head'

const AuthPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Auth Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1>Auth Page</h1>
    </>
  )
}

export default AuthPage
