import type { NextPage } from 'next'
import Head from 'next/head'

import { AuthContent } from 'components/Auth'

const AuthPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Auth Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <AuthContent />
    </>
  )
}

export default AuthPage
