import type { NextPage } from 'next'
import Head from 'next/head'

const NewsPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>News Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1>Здесь пока нет новостей, но они скоро будут =)</h1>
    </>
  )
}

export default NewsPage
