import { Error } from 'components/Error'
import type { NextPage } from 'next'
import Head from 'next/head'

const Error404Page: NextPage = () => {
  return (
    <>
      <Head>
        <title>News Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Error />
    </>
  )
}

export default Error404Page
