import { LINKS } from 'const/links'
import { useAuth } from 'hooks/auth.hook'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { atom_statusAuth } from 'reacoil/atoms/auth'
import { useEffect } from 'react'
import { useRecoilState } from 'recoil'

const HomePage: NextPage = () => {
  const [statusAuth, setStatusAuth] = useRecoilState(atom_statusAuth)

  const router = useRouter()

  useEffect(() => {
    if (!statusAuth) {
      router.push({
        pathname: LINKS.auth
      })
    }
  }, [router, statusAuth])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1>Начальная страница</h1>
    </>
  )
}

export default HomePage
