import type { NextPage } from 'next'
import Head from 'next/head'

import { Tournament } from 'components/Tournament'

const NewsPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>News Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

    <Tournament />
    </>
  )
}

export default NewsPage
